const config = require('./config.json');
global.config = config;
const Vjudge = require('./module/vjudger');
const updateStatusManager = require("./module/updateStatus");
const submitAnalyse = require('./module/submitAnalyse');
//const problem_crawler = require('./module/problem_crawler');
const hdu_judger = new Vjudge(config, "hdu");
const poj_judger = new Vjudge(config, "poj");
const uva_judger = new Vjudge(config, "uva");
const jsk_judger = new Vjudge(config, "jsk");
const bzoj_judger = new Vjudge(config, "bzoj");
const analyse = new submitAnalyse(config);
const vijos_judger = new Vjudge(config, "vijos");
const updateManager = new updateStatusManager();
//const crawler = new problem_crawler(config, 1);
//const updater = new problem_crawler(config);
analyse.start();
